/*
 * generated by Xtext 2.20.0
 */
package rls4eclipse.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import rls4eclipse.ui.internal.Rls4eclipseActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RLSExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Rls4eclipseActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Rls4eclipseActivator activator = Rls4eclipseActivator.getInstance();
		return activator != null ? activator.getInjector(Rls4eclipseActivator.RLS4ECLIPSE_RLS) : null;
	}

}
