/**
 * generated by Xtext 2.20.0
 */
package rls4eclipse.tests;

/*-
 * #%L
 * rls4eclipse.tests
 * %%
 * Copyright (C) 2018 - 2020 rls4eclipse Developers
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.junit.jupiter.api.extension.ExtendWith;
import rls4eclipse.tests.RLSInjectorProvider;

@ExtendWith(InjectionExtension.class)
@InjectWith(RLSInjectorProvider.class)
@SuppressWarnings("all")
public class RLSParsingTest {
}
