/**
 * generated by Xtext 2.20.0
 */
package rls4eclipse.tests;

import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.junit.jupiter.api.extension.ExtendWith;
import rls4eclipse.tests.RLSInjectorProvider;

@ExtendWith(InjectionExtension.class)
@InjectWith(RLSInjectorProvider.class)
@SuppressWarnings("all")
public class RLSParsingTest {
}
