/*
 * generated by Xtext 2.20.0
 */
package rulewerk;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RLSRuntimeModule extends AbstractRLSRuntimeModule {
}
