/*
 * generated by Xtext 2.20.0
 */
package rulewerk;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RLSStandaloneSetup extends RLSStandaloneSetupGenerated {

	public static void doSetup() {
		new RLSStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
