/*
 * generated by Xtext 2.20.0
 */
package rulewerk.validation;

import java.util.HashSet;

import org.eclipse.xtext.validation.Check;

import rulewerk.rLS.*;

/**
 * This class contains custom validation rules.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class RLSValidator extends AbstractRLSValidator {

	@Check
	public void checkUniVars(Rule rule) {
		HashSet<String> a = new HashSet<String>();
		for (Literal l : rule.getBody().getL()) {
			for (Term f : l.getTerms().getT()) {
				a.add(f.getT());
			}
		}
		for (PositiveLiteral x : rule.getHead().getL()) {
			for (Term t : x.getTerms().getT()) {
				if (t.getT().contains("?")) {
					if (!a.contains(t.getT())) {
						error("every universal variable in the head of the rule must also be in the body of the rule",
								rule.eClass().getEStructuralFeature(RLSPackage.RULE));
					}
				}
			}
		}

	}

	@Check
	public void checkMalformedRule(Rule rule) {
		HashSet<String> a = new HashSet<String>();
		for (Literal l : rule.getBody().getL()) {
			for (Term f : l.getTerms().getT()) {
				if (f.getT().startsWith("?")) {
					a.add(f.getT().replace("?", ""));
				}
			}
		}
		for (PositiveLiteral x : rule.getHead().getL()) {
			for (Term t : x.getTerms().getT()) {
				if (t.getT().startsWith("!")) {
					String s = t.getT().replace("!", "");
					if (a.contains(s)) {
						error("Variable that is existentially quantified in the head cannot be universally quantified in the body of the rule",
								rule.eClass().getEStructuralFeature(RLSPackage.RULE));
					}
				}
			}
		}

	}

	@Check
	public void checkExiVars(Rule rule) {
		for (Literal l : rule.getBody().getL()) {
			for (Term f : l.getTerms().getT()) {
				if (f.getT().startsWith("!")) {
					error("Existentialy quantified variables can not appear in the body of the rule",
							rule.eClass().getEStructuralFeature(RLSPackage.RULE));
				} else if (f.getT().startsWith("_:")) {
					error("Named nulls can not appear in the body of the rule",
							rule.eClass().getEStructuralFeature(RLSPackage.RULE));
				}
			}
		}

	}

}
