/*
 * generated by Xtext 2.20.0
 */
package rls4eclipse.ui;

/*-
 * #%L
 * rls4eclipse.ui
 * %%
 * Copyright (C) 2018 - 2020 rls4eclipse Developers
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.IXtextEditorCallback;
import org.eclipse.xtext.ui.editor.IXtextEditorCallback.NullImpl;
import org.eclipse.xtext.ui.editor.outline.IOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.validation.ValidatingEditorCallback;
import org.eclipse.xtext.ui.refactoring.IRenameStrategy;

import com.google.inject.Binder;
import com.google.inject.name.Names;

import rls4eclipse.ui.contentassist.AbstractRLSProposalProvider;
import rls4eclipse.ui.contentassist.RLSProposalProvider;
import rls4eclipse.ui.outline.RLSOutlineTreeProvider;
import rls4eclipse.ui.renaming.RenameRefactor;
import rls4eclipse.ui.syntaxhighlighting.CLHighlightingConfiguration;
//import rls4eclipse.ui.syntaxhighlighting.CLHighlightingConfiguration;
import rls4eclipse.ui.syntaxhighlighting.SemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@SuppressWarnings("restriction")
public class RLSUiModule extends AbstractRLSUiModule {

	public RLSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends ISemanticHighlightingCalculator> bindisemantichighlightingcalculator() {
		return SemanticHighlightingCalculator.class;
	}

	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return CLHighlightingConfiguration.class;
	}

	public Class<? extends AbstractRLSProposalProvider> bindAbstractMyDslProposalProvider() {
		return RLSProposalProvider.class;
	}
	 public Class<? extends IOutlineTreeProvider> bindIOutlineTreeProvider() {
	 return RLSOutlineTreeProvider.class;
}

	public Class<? extends IXtextEditorCallback> bindIXtextEditorCallback() {
		return NullImpl.class;
	}
	
	@Override
	public Class<? extends IRenameStrategy> bindIRenameStrategy() {
		return RenameRefactor.class;
	}
	
	public void configureMarkOccurrencesAction2(Binder binder) {
		binder.bind(IXtextEditorCallback.class).annotatedWith(Names.named("RuleWerkValidation"))
			.to(ValidatingEditorCallback.class);
	}
	
	
}
