/*
 * generated by Xtext 2.20.0
 */
package rulewerk.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.IXtextEditorCallback;
import org.eclipse.xtext.ui.editor.IXtextEditorCallback.NullImpl;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

import rulewerk.ui.contentassist.AbstractRLSProposalProvider;
import rulewerk.ui.contentassist.RLSProposalProvider;
import rulewerk.ui.syntaxhighlighting.CLHighlightingConfiguration;
import rulewerk.ui.syntaxhighlighting.SemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RLSUiModule extends AbstractRLSUiModule {

	public RLSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends ISemanticHighlightingCalculator> bindisemantichighlightingcalculator() {
		return SemanticHighlightingCalculator.class;
	}

	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return CLHighlightingConfiguration.class;
	}

	public Class<? extends AbstractRLSProposalProvider> bindAbstractMyDslProposalProvider() {
		return RLSProposalProvider.class;
	}
	// public Class<? extends IOutlineTreeProvider> bindIOutlineTreeProvider() {
	// return RuleLangOutlineTreeProvider.class;
//	}

	public Class<? extends IXtextEditorCallback> bindIXtextEditorCallback() {
		return NullImpl.class;
	}
}
