/*
 * generated by Xtext 2.20.0
 */
package rls4eclipse.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import rls4eclipse.ui.internal.Rls4eclipseActivator;

public class RLSUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Rls4eclipseActivator.getInstance().getInjector("rls4eclipse.RLS");
	}

}
