/*
 * generated by Xtext 2.20.0
 */
package rulewerk.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class RLSOutlineTreeProvider extends DefaultOutlineTreeProvider {
	// protected void _createChildren(DocumentRootNode parentNode, EObject
		// modelElement) {
		// createNode(parentNode, modelElement);
		// }

	/*	@Override
		protected void _createChildren(IOutlineNode parentNode, EObject modelElement) {
			for (EObject a : modelElement.eContents()) {
				Object text = textDispatcher.invoke(a);
				System.out.println(text);
				if (!text.equals("Body")) {
					createNode(parentNode, a);
				}
			}
		}*/

		//protected void _createNode(IOutlineNode parentNode, Rule modelElement) {
		// }

		/*
		 * protected void _createChildren(DocumentRootNode parentNode, EObject
		 * modelElement) { for (EObject a : modelElement.eContents()) { if (a instanceof
		 * Statement) { Object text = textDispatcher.invoke(a);
		 * System.out.println(text); } else { createNode(parentNode, a); }
		 * 
		 * } }
		 */
}
