/*
 * generated by Xtext 2.20.0
 */
package rulewerk.ui.labeling;

import com.google.inject.Inject;

import rulewerk.rLS.Literal;
import rulewerk.rLS.NegativeLiteral;
import rulewerk.rLS.PositiveLiteral;
import rulewerk.rLS.Rule;
import rulewerk.rLS.Statement;
import rulewerk.rLS.listOfLiterals;
import rulewerk.rLS.listOfPositiveLiterals;
import rulewerk.rLS.listOfTerms;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class RLSLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public RLSLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	String text(Rule r) {
		return "Rule";
	}
	
	String text(Statement s) {
		return "Statement";
	}
	
	String text(listOfPositiveLiterals h) {
		return "Head";
	}
	
	String text(listOfLiterals s) {
		return "Body";
	}
	
	String text(Literal s) {
		return "Predicate name";
	}
	
	String text(PositiveLiteral s) {
		return "Positive Literal";
	}
	
	String text(NegativeLiteral s) {
		return "Negative Literal";
	}
	
	String text(listOfTerms s) {
		return "Terms";
	}
//
//	String image(Greeting ele) {
//		return "Greeting.gif";
//	}
}
